android {
    namespace "com.davidsanchez.elcontrastenoticiasapp"
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }

    defaultConfig {
        applicationId "com.davidsanchez.elcontrastenoticiasapp"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 7
        versionName "1.6"
    }
}